### PR TITLE
Added products endpoint

### PR DESCRIPTION
**Pull request by zimmerel**
Added get_product and get_all_products endpoints for the API (which are still experimental)

### CODE REVIEW

**Comment by zimmerel** [comment]
I haven't added any tests yet. I have tested them personally on my company's account and they work great, but feel free to reject if you want me to write them before committing.

**Comment by jpetrucciani** [comment]
Awesome! Thanks for the contribution 😄 

I'll touch up just a couple of things then I'll get a build out on pip!

**Comment by zimmerel** [comment]
No problem! I've been trying to commit for a while, I've just been so tied up. I hope to have some more contributions soon!

**Comment by jpetrucciani** [comment]
This should be live now on pip as version `3.2.10`!

The only touch-ups I made are:
- formatting the new file with [black](https://github.com/python/black)
- full path imports (I just prefer it this way for explicitness)
- changing the f-string back to `.format()` syntax (I love f-strings, don't get me wrong! But I do want this to work on 3.5/6 for now)

Thanks again for the contributions - looking forward to more! 😄

**Comment by zimmerel** [comment]
Awesome! I'll keep black in mind for my next PR, I've never used it for but it makes a lot of sense for collaboration.

Also, I totally meant to replace the f strings with the .format, but I forgot about them. I'll take care for next time. I use them all the time in production code and they are too handy and readable, so I tend to forget I'm even using them.

**Comment by jpetrucciani** [comment]
No worries! I love f-strings too, I wish they had been added to python earlier!

I was hesitant about using black at first, but now I use it on everything - it's so convenient to not have to worry about style anymore, and once all your files use that consistent style, they become easier to read/comprehend in my opinion. Plus, you can just add it on save to your editor (I personally use [sublack](https://github.com/jgirardet/sublack), but there should be addons/plugins for most editors)!

Thanks again for your contributions! 😄

**Pull request merged**
