### PR TITLE
Missing API endpoints (bridge, deals, line items)

### PR DESCRIPTION
**Pull request by hkage**
Hi there,

this PR adds some missing endpoints for different API clients:

* Check the sync status of an object (https://developers.hubspot.com/docs/methods/ecommerce/v2/check-sync-status)
* Delete a line item (https://developers.hubspot.com/docs/methods/line-items/delete-line-item)
* Delete a Deal (https://developers.hubspot.com/docs/methods/deals/delete_deal)

A small note: due to the fact that all deal tests currently use your development Hubspot account I added a test for the deal deletion that actually creates and deletes a deal (to not differ from the other test implementations). That can cause CI errors if the maximum request limit was reached. It would be the best to refactor those test and to mock out the Hubspot calls, but I guess you already discussed that topic with some of my colleagues.

### CODE REVIEW

**Comment by jpetrucciani** [comment]
Awesome - I'll review and merge in soon!

**Comment by hkage** [comment]
Thank you!

**Comment by jpetrucciani** [comment]
This is now live on pip as version [`3.2.27`](https://github.com/jpetrucciani/hubspot3/releases/tag/3.2.27)

Thanks for your contributions! 😄

**Comment by hkage** [comment]
Great :+1: Thanks for the quick review and release.

**Pull request merged**
